#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

void disassemble_opcode(uint16_t opcode, uint16_t pc, FILE *out) {
    uint8_t x = (opcode & 0x0F00) >> 8;
    uint8_t y = (opcode & 0x00F0) >> 4;
    uint8_t n = opcode & 0x000F;
    uint8_t kk = opcode & 0x00FF;
    uint16_t nnn = opcode & 0x0FFF;

    switch (opcode & 0xF000) {
        case 0x0000:
            if (opcode == 0x00E0) fprintf(out, "CLS");
            else if (opcode == 0x00EE) fprintf(out, "RET");
            else fprintf(out, "SYS 0x%03X", nnn);
            break;
        case 0x1000: fprintf(out, "JP 0x%03X", nnn); break;
        case 0x2000: fprintf(out, "CALL 0x%03X", nnn); break;
        case 0x3000: fprintf(out, "SE V%X, 0x%02X", x, kk); break;
        case 0x4000: fprintf(out, "SNE V%X, 0x%02X", x, kk); break;
        case 0x5000: fprintf(out, "SE V%X, V%X", x, y); break;
        case 0x6000: fprintf(out, "LD V%X, 0x%02X", x, kk); break;
        case 0x7000: fprintf(out, "ADD V%X, 0x%02X", x, kk); break;
        case 0x8000:
            switch (opcode & 0x000F) {
                case 0x0: fprintf(out, "LD V%X, V%X", x, y); break;
                case 0x1: fprintf(out, "OR V%X, V%X", x, y); break;
                case 0x2: fprintf(out, "AND V%X, V%X", x, y); break;
                case 0x3: fprintf(out, "XOR V%X, V%X", x, y); break;
                case 0x4: fprintf(out, "ADD V%X, V%X", x, y); break;
                case 0x5: fprintf(out, "SUB V%X, V%X", x, y); break;
                case 0x6: fprintf(out, "SHR V%X, V%X", x, y); break;
                case 0x7: fprintf(out, "SUBN V%X, V%X", x, y); break;
                case 0xE: fprintf(out, "SHL V%X, V%X", x, y); break;
                default: fprintf(out, "UNK 0x%04X", opcode); break;
            }
            break;
        case 0x9000: fprintf(out, "SNE V%X, V%X", x, y); break;
        case 0xA000: fprintf(out, "LD I, 0x%03X", nnn); break;
        case 0xB000: fprintf(out, "JP V0, 0x%03X", nnn); break;
        case 0xC000: fprintf(out, "RND V%X, 0x%02X", x, kk); break;
        case 0xD000: fprintf(out, "DRW V%X, V%X, %d", x, y, n); break;
        case 0xE000:
            if (kk == 0x9E) fprintf(out, "SKP V%X", x);
            else if (kk == 0xA1) fprintf(out, "SKNP V%X", x);
            else fprintf(out, "UNK 0x%04X", opcode);
            break;
        case 0xF000:
            switch (kk) {
                case 0x07: fprintf(out, "LD V%X, DT", x); break;
                case 0x0A: fprintf(out, "LD V%X, K", x); break;
                case 0x15: fprintf(out, "LD DT, V%X", x); break;
                case 0x18: fprintf(out, "LD ST, V%X", x); break;
                case 0x1E: fprintf(out, "ADD I, V%X", x); break;
                case 0x29: fprintf(out, "LD F, V%X", x); break;
                case 0x33: fprintf(out, "LD B, V%X", x); break;
                case 0x55: fprintf(out, "LD [I], V%X", x); break;
                case 0x65: fprintf(out, "LD V%X, [I]", x); break;
                default: fprintf(out, "UNK 0x%04X", opcode); break;
            }
            break;
        default:
            fprintf(out, "UNK 0x%04X", opcode);
            break;
    }
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        printf("Usage: %s <input.ch8> <output.asm>\n", argv[0]);
        printf("Example: %s pong.ch8 pong.asm\n", argv[0]);
        return 1;
    }

    // Open input ROM file
    FILE *input = fopen(argv[1], "rb");
    if (!input) {
        printf("Error: Cannot open input file '%s'\n", argv[1]);
        return 1;
    }

    // Open output assembly file
    FILE *output = fopen(argv[2], "w");
    if (!output) {
        printf("Error: Cannot create output file '%s'\n", argv[2]);
        fclose(input);
        return 1;
    }

    // Get file size
    fseek(input, 0, SEEK_END);
    long file_size = ftell(input);
    fseek(input, 0, SEEK_SET);

    // Allocate memory for ROM
    uint8_t *rom = malloc(file_size);
    if (!rom) {
        printf("Error: Memory allocation failed\n");
        fclose(input);
        fclose(output);
        return 1;
    }

    // Read ROM file
    size_t bytes_read = fread(rom, 1, file_size, input);
    if (bytes_read != file_size) {
        printf("Error: Failed to read ROM file\n");
        free(rom);
        fclose(input);
        fclose(output);
        return 1;
    }

    // Write header to output file
    fprintf(output, "; CHIP-8 Disassembly of '%s'\n", argv[1]);
    fprintf(output, "; Generated by CHIP-8 Disassembler\n");
    fprintf(output, "; PC     Opcode   Instruction\n");
    fprintf(output, "; ---------------------------\n");

    // Disassemble each instruction
    for (int pc = 0x200; pc < file_size; pc += 2) {
        if (pc + 1 >= file_size) break;

        uint16_t opcode = (rom[pc] << 8) | rom[pc + 1];
        
        // Write PC address and opcode
        fprintf(output, "0x%04X: 0x%04X  ", pc, opcode);
        
        // Write instruction
        disassemble_opcode(opcode, pc, output);
        fprintf(output, "\n");
    }

    // Cleanup
    free(rom);
    fclose(input);
    fclose(output);

    printf("Disassembly complete: '%s' -> '%s'\n", argv[1], argv[2]);
    return 0;
}
